### ISSUE TITLE
unable to flash the firmware

### ISSUE THREAD

**Issue by ric-tim** [Protoneer/RPI-CNC-Config-Scripts#3]
[Solved] i had to use the script 007-install-Arduino.sh
You have a bug in avrdude-rpi/avrdude-autoreset arduino-1.8.10 and not arduino-1.8.5

Thanks a lot for this RPI-CNC !

**Comment by Protoneer** [comment]
Thanks.

I have fixed. HAve moved away from folders with Version numbers in it to prevent these issues in the future.
