### ISSUE TITLE
Error running in Run-Flash-GRBL-Latest.sh

### ISSUE THREAD

**Issue by IHadToPickaUsername** [Protoneer/RPI-CNC-Config-Scripts#4]
Running Run-Flash-GRBL-Latest.sh throws an error :

`RPI-ATMega328
strace: Can't stat '/home/pi/arduino-1.8.5/hardware/tools/avr/bin/avrdude-original': No such file or directory
sh: 1: /home/pi/arduino-1.8.5/hardware/tools/avr/bin/autoreset328: not found`

Which comes from multiple path errors in the avrdude-autoreset file (arduino path : 1.8.5 instead of 1.8.10)

Original :
`#!/bin/bash
if [[ $@ == *atmega2560* && $@ == */dev/ttyAMA0* ]]
then
  echo "RPI-ATMega2560";
  sudo strace -o "|/home/pi/arduino-1.8.5/hardware/tools/avr/bin/autoreset2560" -eioctl /home/pi/arduino-1.8.5/hardware/tools/avr/bin/avrdude-original $@
elif [[ $@ == *atmega328* && $@ == */dev/ttyAMA0* ]]
then
  echo "RPI-ATMega328";
  sudo strace -o "|/home/pi/arduino-1.8.5/hardware/tools/avr/bin/autoreset328" -eioctl /home/pi/arduino-1.8.5/hardware/tools/avr/bin/avrdude-original $@
else
  sudo /home/pi/arduino-1.8.5/hardware/tools/avr/bin/avrdude-original $@
fi
`

Fixed :
`#!/bin/bash
if [[ $@ == *atmega2560* && $@ == */dev/ttyAMA0* ]]
then
  echo "RPI-ATMega2560";
  sudo strace -o "|/home/pi/arduino-1.8.10/hardware/tools/avr/bin/autoreset2560" -eioctl /home/pi/arduino-1.8.10/hardware/tools/avr/bin/avrdude-original $@
elif [[ $@ == *atmega328* && $@ == */dev/ttyAMA0* ]]
then
  echo "RPI-ATMega328";
  sudo strace -o "|/home/pi/arduino-1.8.10/hardware/tools/avr/bin/autoreset328" -eioctl /home/pi/arduino-1.8.10/hardware/tools/avr/bin/avrdude-original $@
else
  sudo /home/pi/arduino-1.8.10/hardware/tools/avr/bin/avrdude-original $@
fi
`

**Comment by Protoneer** [comment]
Thanks for that. I will fix it with the next release.

**Comment by Protoneer** [comment]
I have updated this...

https://github.com/Protoneer/RPI-CNC-Config-Scripts/blob/master/scripts/avrdude-rpi/avrdude-autoreset

I have moved away from having Arduino folders with version number in them.

Thanks
